embedding_model: "pritamdeka/BioBERT-mnli-snli-scinli-scitail-mednli-stsb"
vector_top_k: 8
rerank_top_k: 4
chunk_size: 512
chunk_overlap: 50
max_tokens_output: 1024
temperature: 0.1
chroma_path: "./data/chroma_db"
collection_name: "medical_knowledge"